// Auto-generated image paths - extracted from base64 HTML
export const IMAGES = {
  logo: '/images/img-1.png',
  screenshotMyOI: '/images/img-2.jpg',
  screenshotCommandCentre: '/images/img-3.jpg',
  avatarConsult1: '/images/img-4.jpg',
  avatarConsult2: '/images/img-5.jpg',
  avatarConsult3: '/images/img-6.jpg',
  avatarConsult4: '/images/img-7.jpg',
  avatarConsult5: '/images/img-8.jpg',
  avatarConsult6: '/images/img-9.jpg',
  avatarConsult7: '/images/img-10.jpg',
  avatarConsult8: '/images/img-11.jpg',
  avatarConsult9: '/images/img-12.jpg',
  avatarConsult10: '/images/img-13.jpg',
  avatarConsult11: '/images/img-14.jpg',
  avatarConsult12: '/images/img-15.jpg',
  avatarConsult13: '/images/img-16.jpg',
  avatarConsult14: '/images/img-17.jpg',
  screenshotProjects: '/images/img-18.jpg',
  screenshotTasks: '/images/img-19.jpg',
  screenshotConversations: '/images/img-20.jpg',
  hardwareAppliance: '/images/img-21.png',
  logoIn2Equity: '/images/img-22.png',
  logoFHDepot: '/images/img-23.png',
  logoFortwell: '/images/img-24.png',
  logoSocialHouse: '/images/img-25.png',
  logoOmfinitive: '/images/img-26.png',
  logoMercuryCareers: '/images/img-27.png',
  logoHyphenConnect: '/images/img-28.png',
  logoHyphenLabs: '/images/img-29.png',
  logoHyphenONE: '/images/img-30.png',
  logoHyphenExchange: '/images/img-31.png',
  // Ticker aliases (same as first 4 consultant avatars)
  tickerAdwoa: '/images/img-4.jpg',
  tickerJames: '/images/img-5.jpg',
  tickerKwame: '/images/img-6.jpg',
  tickerPriya: '/images/img-7.jpg',
} as const;
